---
title: "Faces_Piloting_V2"
author: "Oris Shenyan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(binom)
library(ggpubr)
```

```{r}
#Set up
subnumber <- '030'
gender <- 'male'
age <- '26'
```

```{r}
folder_path <- "Pilot1_output"

#create folder if it doesn't exist
if (!dir.exists(folder_path)) {
  dir.create(folder_path, recursive = TRUE)
}
```


```{r}
# Step 1: Read CSV files and add a 'Block' column
data_list <- lapply(0:6, function(i) {
  # Read each CSV file
  df <- read.csv(paste0("data/sub", subnumber, "_", gender, "_", age, "_training2block00", i, ".csv"))
  # Add a 'Block' column based on the file name
  df$Block <- paste("Block", i, sep="")
  return(df)
})

# Combine all data frames into one
combined_data <- bind_rows(data_list)
```
## Opacity vs proportion of faces identified
```{r}
summarised_data <- combined_data %>%
  group_by(Opacity) %>%
  summarise(Proportion_Identified = sum(Realface_response) / n())
```

```{r}
model <- glm(Realface_response ~ Opacity, family = binomial, data = combined_data)

# Extract model coefficients
beta_0 <- coef(model)[1]
beta_1 <- coef(model)[2]

inflection_point <- -beta_0 / beta_1
```


```{r}
# Plot
plot <- ggplot(summarised_data, aes(x = Opacity, y = Proportion_Identified)) +
  geom_point(alpha = 0.7, size = 2) +
  stat_smooth(method = "glm", method.args = list(family = "binomial"), se = FALSE, color = "blue") +
  geom_vline(xintercept = inflection_point, linetype = "dashed", color = "red") +
  annotate("text", x = inflection_point, y = 0.5, label = paste("Threshold:", round(inflection_point, 2)), hjust = -0.2, vjust = -0.5, color = "red") +
  theme_minimal() +
  labs(title = paste0("Participant ", subnumber, " (",gender,', ',age,"): ", "Proportion of faces perceived vs opacity of faces"),
       x = "Opacity level",
       y = "Proportion of faces identified",
       subtitle = "Inflection point (sensory threshold) marked by red dashed line")

ggsave(filename = paste0("Pilot1_output/opacityplot_training2_", subnumber, "_", age, "_", gender, ".png"), plot = plot, device = "png")

```

## Confidence
```{r}
#filter
filtered_data_confidence <- combined_data %>%
  filter(Realface_response == 1) 

# Assuming your dataframe is named df
plot1 <- ggplot(filtered_data_confidence, aes(x = Realface_confidence)) +
  geom_histogram(binwidth = 1, fill = "blue", color = "black", alpha = 0.7) +
  facet_wrap(~Opacity, scales = "free_y") +
  theme_minimal() +
  labs(title = paste0("Participant ", subnumber, " (",gender,', ',age,"): ", "Distribution of confidence ratings \n  across opacity levels"),
       x = "Confidence Rating",
       y = "Frequency")

ggsave(filename = paste0("Pilot1_output/confidenceplot_training2_", subnumber, "_", age, "_", gender, ".png"), plot = plot1, device = "png")

```
## Direction

```{r}

direction_df <- filtered_data_confidence %>%
  mutate(Face_Position_Clean = as.numeric(trimws(as.character(Face_Position)))) %>% 
  mutate(Correct_Direction = ifelse(
    ((Direction == 'right' & Face_Position_Clean %in% c(5, 7)) | 
     (Direction == 'left' & Face_Position_Clean %in% c(-5, -7))),
    1, 
    0
  )) 
```


```{r}
direction_df_summary <- direction_df %>%
  group_by(Opacity) %>%
  summarise(Proportion_Correct = sum(Correct_Direction) / n())
```

```{r}
plot2 <- ggplot(direction_df_summary, aes(x = Opacity, y = Proportion_Correct)) +
  geom_line() +  # Line plot
  geom_point() +  # Add points
  labs(title = paste0("Participant ", subnumber, " (",gender,', ',age,"): ", "Accuracy of identifying direction of faces by opacity"),
       x = "Opacity",
       y = "Accuracy") +
      geom_vline(xintercept = inflection_point, linetype = "dashed", color = "red") +
  annotate("text", x = inflection_point, y = 0.5, label = paste("Threshold:", round(inflection_point, 2)), hjust = -0.2, vjust = -35, color = "red") +
  labs(title = paste0("Participant ", subnumber, " (",gender,', ',age,"): ", "Accuracy of identifying direction of faces by opacity"),
       x = "Opacity",
       y = "Accuracy") +
  scale_x_continuous(breaks = seq(from = min(direction_df_summary$Opacity), to = max(direction_df_summary$Opacity), by = 0.1)) +
  theme_minimal()

ggsave(filename = paste0("Pilot1_output/directionplot_training2_", subnumber, "_", age, "_", gender, ".png"), plot = plot2, device = "png")
```

